name: Generate Version Changelog
description: Generate new semver, bump the tag, update CHANGELOG.md in one commit
author: bendevcat
branding:
  icon: align-left
  color: green
inputs:
# Changelog
  token:
    description: Github repository token
    required: true
  exclude_types:
    description: 'Which commit types to exclude from the changelog, comma separated string (example: "other,chore")'
    required: false
  config_file:
    description: Location of the config JSON file
    required: false
# Version
  tag-prefix:
    description: 'Prefix that is used for the git tag'
    default: ''
    required: false
  minor-wording:
    description: 'Words list that trigger a minor version bump'
    default: 'feat,minor'
    required: false
  major-wording:
    description: 'Words list that trigger a major version bump'
    default: 'BREAKING CHANGE,major'
    required: false
  patch-wording:
    description: 'Words list that trigger a patch version bump'
    required: false
  rc-wording:
    description: 'Words list that trigger a rc version bump'
    default: 'pre-alpha,pre-beta,pre-rc'
    required: false
  skip-tag:
    description: 'Avoid to add a TAG to the version update commit'
    default: 'false'
    required: false
  PACKAGEJSON_DIR:
    description: 'Custom dir to the package'
    default: ''
    required: false
  target-branch:
    description: 'A separate branch to perform the version bump on'
    default: ''
    required: false
  default:
    description: 'Set a default version bump to use'
    default: 'patch'
    required: false
  preid:
    description: 'Set a custom preid for prerelease build'
    default: 'rc'
    required: false
  commit-message:
    description: 'Set a custom commit message for version bump commit'
    default: ''
    required: false
  push:
    description: 'Set to false to skip pushing the new tag'
    default: 'true'
    required: false
outputs:
  changelog:
    description: Generated changelog for the latest tag
  changes:
    description: Generated changelog for the latest tag, without the version/date header
  newTag:
    description: 'The newly created tag'
runs:
  using: node12
  main: "dist/index.js"
